$axure.loadCurrentPage({
  "url":"schedule.html",
  "generationDate":new Date(1376533202930.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"DroplistOption"],
  "page":{
    "packageId":"10475b848363471390e901127df49ff3",
    "type":"Axure:Page",
    "name":"Schedule",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"25",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"Set is selected of Default Window/Schedule equal to &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["dc8804fc29bd4d62be344237007bcfa3",
"0b97a9aadb1b4ebf81ad1e88d6e74327"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"dc8804fc29bd4d62be344237007bcfa3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"1d0592bb516a414fa8b800f785045d87"},
{
          "id":"bf373003968c4fa8b9b3bb6463f0bd7e",
          "label":"Save/Revert Modal",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":9,
              "y":9.19999694824219},
            "size":{
              "width":530,
              "height":322},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f1e012e55083443a8a99dc35889f5425",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e82ca91a31dd4ea486141dadebbd0fce",
                  "label":"",
                  "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FCCCCCC},
                    "size":{
                      "width":530,
                      "height":322}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fff40588fd2d435189d79634dba8dfa1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7FCCCCCC},
                        "size":{
                          "width":530,
                          "height":322}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/u18.png"}},
{
                  "id":"102e52f04a4543b2ade04beff9e6e798",
                  "label":"ModalStatusText",
                  "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontWeight":"bold",
                    "location":{
                      "x":189,
                      "y":113},
                    "size":{
                      "width":180,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef9d60b400ea4093a94b7bd9b9fcc999",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontWeight":"bold",
                        "location":{
                          "x":189,
                          "y":113},
                        "size":{
                          "width":180,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/modalstatustext_u20.png"}},
{
                  "id":"63312ec219a74afcb9969f5106af98b6",
                  "label":"Loading Small",
                  "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":323,
                      "y":145},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c0a6cadc7cc4b2fa8f37e8c48fa0453",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":323,
                          "y":145},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/loading_small_u22.gif"}}]}]},
{
          "id":"dbd9a4c8cc2c4a91be97c179d9554437",
          "label":"Schedule Text",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":52},
            "size":{
              "width":499,
              "height":25}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Allows user to type in a schedule, or it displays what the user has selected below."}},
{
          "id":"2a3422d0fa354cadb354d6bc0f8249e4",
          "label":"Save Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":352,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28398e60abec4b0fa2dd232722e3123e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":352,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Saving...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["ef9d60b400ea4093a94b7bd9b9fcc999"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Saving...</span></p>",
                                "localVariables":{
},
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Send Save/Revert Modal to Back",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":false}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Save Changes on this Screen"},
          "images":{
            "normal~":"images/tags/save_changes_u30.png",
            "mouseOver~":"images/tags/save_changes_u30.png"}},
{
          "id":"f9b078766bac4262b075ec284185010c",
          "label":"Revert Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":444,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b149ef0e894d3790f133b6475d556e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":444,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Reverting...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["ef9d60b400ea4093a94b7bd9b9fcc999"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Reverting...</span></p>",
                                "localVariables":{
},
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Send Save/Revert Modal to Back",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":false}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Revert changes to the settings prior to loading the page."},
          "images":{
            "normal~":"images/tags/revert_changes_u32.png",
            "mouseOver~":"images/tags/revert_changes_u32.png"}},
{
          "id":"c21533eb798040b398ccb37fcb821492",
          "label":"Suspend Notifcations",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "location":{
              "x":322,
              "y":88},
            "size":{
              "width":202,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"984c7f881af741cb9f5ee2e92f6a1667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "location":{
                  "x":322,
                  "y":88},
                "size":{
                  "width":202,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If is selected of Suspend Notifcations equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["c21533eb798040b398ccb37fcb821492"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"Disable Recurrence,<br>Mid Morning,<br>Mid Afternoon,<br>Noon,<br>Morning,<br>Early Morning,<br>Schedule Text,<br>Afternoon,<br>Late Night,<br>Evening",
                      "pathToInfo":[{
                          "objectPath":["107a9995965a406992c01e6b37ad9cd9"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["0ee2562200124b74b8f4a4fe560608ed"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["fd32dd8921ea4e7aad253e8d3c1f9347"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["eb6630df47db473dbd6bede25aabfefa"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["02c9b65dba2f47a2adbce2d050c88717"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["83cd9b3cec2b43b5a0032cde91c80da7"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["dbd9a4c8cc2c4a91be97c179d9554437"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["4abb932073894f878506dea2b953705c"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["eb9f17e19e5a4cb693d1eb3553117700"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["0281a5f023f14fddbe4bee543dedccdd"],
                          "enableDisableInfo":{
                            "enable":false}}]}]},
{
                  "description":"Case 2<br> (Else If is selected of Suspend Notifcations equals false)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["c21533eb798040b398ccb37fcb821492"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"Enable Schedule Text,<br>Early Morning,<br>Morning,<br>Noon,<br>Mid Afternoon,<br>Mid Morning,<br>Recurrence,<br>Evening,<br>Late Night,<br>Afternoon",
                      "pathToInfo":[{
                          "objectPath":["dbd9a4c8cc2c4a91be97c179d9554437"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["83cd9b3cec2b43b5a0032cde91c80da7"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["02c9b65dba2f47a2adbce2d050c88717"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["eb6630df47db473dbd6bede25aabfefa"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["fd32dd8921ea4e7aad253e8d3c1f9347"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["0ee2562200124b74b8f4a4fe560608ed"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["107a9995965a406992c01e6b37ad9cd9"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["0281a5f023f14fddbe4bee543dedccdd"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["eb9f17e19e5a4cb693d1eb3553117700"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["4abb932073894f878506dea2b953705c"],
                          "enableDisableInfo":{
                            "enable":true}}]}]}]}}},
{
          "id":"83cd9b3cec2b43b5a0032cde91c80da7",
          "label":"Early Morning",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":127},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3116ce60b4a54fd18cee923bb0512d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":127},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"02c9b65dba2f47a2adbce2d050c88717",
          "label":"Morning",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":170},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e094edbb5cd8441c80071f287748d271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":170},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"eb6630df47db473dbd6bede25aabfefa",
          "label":"Noon",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":251},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81c37459f541483db4e1010161b74f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":251},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"fd32dd8921ea4e7aad253e8d3c1f9347",
          "label":"Mid Afternoon",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":125},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27e26a75899440e873b0b3709eecc73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":125},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"0ee2562200124b74b8f4a4fe560608ed",
          "label":"Mid Morning",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":211},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adffdfe186e34563987b33be07270aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":211},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"4abb932073894f878506dea2b953705c",
          "label":"Afternoon",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":168},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e1a36dafc44e36a94522db14b9c28f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":168},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"eb9f17e19e5a4cb693d1eb3553117700",
          "label":"Late Night",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":250},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fa9e83bf90340ec832c5123cb5bba02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":250},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"0281a5f023f14fddbe4bee543dedccdd",
          "label":"Evening",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":210},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3729a1510f3d468a87f53ab7869aaa6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":210},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"107a9995965a406992c01e6b37ad9cd9",
          "label":"Recurrence",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":85},
            "size":{
              "width":202,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "1d0592bb516a414fa8b800f785045d87":{
      "packageId":"1d0592bb516a414fa8b800f785045d87",
      "type":"Axure:Master",
      "name":"Default Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd52a235e2b14d2abfa6555b2ece48e1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":530,
                "height":317}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a68fbf401bd468b869c5cb7dd1805bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":10},
                  "size":{
                    "width":530,
                    "height":317}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"20a59c4b535c416baab96a462c880970",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":531,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ac3c7732bf5044fa8054f0d8385529c2",
                "label":"Navigation",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "location":{
                    "x":3,
                    "y":3},
                  "size":{
                    "width":525,
                    "height":20}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"1f49a2bfeb324fe3874615bd77106242",
                    "label":"Home",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62cd4166ce5f41e58c21ab9aa43a0eb7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Dashboard in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"dashboard.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"819ac8a5aeba4eeca8fb7de2d6d8d6de",
                    "label":"Tags",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":100,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6d08094da54147e6b1ee2f049735a9f0",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":100,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Tags in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"tags.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"0b97a9aadb1b4ebf81ad1e88d6e74327",
                    "label":"Schedule",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":200,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9d47f61c666a4862bf3794d188181ef2",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":200,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Schedule in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"schedule.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"86ab48f766ea481bb5f1a7199a5b78f8",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":492,
                        "y":0},
                      "size":{
                        "width":33,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"160d7455f130416fa6d81dc2a0264d94",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":492,
                            "y":0},
                          "size":{
                            "width":33,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u15.png",
                      "selected~":"images/dashboard/u15.png",
                      "mouseOver~":"images/dashboard/u15.png"}},
{
                    "id":"9167aff36ce0446c8cecb1c6c2196fd3",
                    "label":"Logout",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":400,
                        "y":0},
                      "size":{
                        "width":92,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f05d90b2abc54df48dbf10ade98840e5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":400,
                            "y":0},
                          "size":{
                            "width":92,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Login in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"login.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/logout_u13.png",
                      "selected~":"images/dashboard/logout_u13.png",
                      "mouseOver~":"images/dashboard/logout_u13.png"}},
{
                    "id":"8d035b185fb84392afc1199c60a7c075",
                    "label":"Recipients",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":300,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"32415f9939704c9d9f7ece4c939a347c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":300,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Recipients in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"recipients.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}}]}],
            "annotation":{
              "Description":"Bold the text of the corresponding button, to indicate the current location to the user."}}]}}},
  "objectPaths":{
    "dc8804fc29bd4d62be344237007bcfa3":{
      "scriptId":"u0",
      "fd52a235e2b14d2abfa6555b2ece48e1":{
        "scriptId":"u1"},
      "7a68fbf401bd468b869c5cb7dd1805bf":{
        "scriptId":"u2"},
      "20a59c4b535c416baab96a462c880970":{
        "scriptId":"u3"},
      "ac3c7732bf5044fa8054f0d8385529c2":{
        "scriptId":"u4"},
      "1f49a2bfeb324fe3874615bd77106242":{
        "scriptId":"u5"},
      "62cd4166ce5f41e58c21ab9aa43a0eb7":{
        "scriptId":"u6"},
      "819ac8a5aeba4eeca8fb7de2d6d8d6de":{
        "scriptId":"u7"},
      "6d08094da54147e6b1ee2f049735a9f0":{
        "scriptId":"u8"},
      "0b97a9aadb1b4ebf81ad1e88d6e74327":{
        "scriptId":"u9"},
      "9d47f61c666a4862bf3794d188181ef2":{
        "scriptId":"u10"},
      "8d035b185fb84392afc1199c60a7c075":{
        "scriptId":"u11"},
      "32415f9939704c9d9f7ece4c939a347c":{
        "scriptId":"u12"},
      "9167aff36ce0446c8cecb1c6c2196fd3":{
        "scriptId":"u13"},
      "f05d90b2abc54df48dbf10ade98840e5":{
        "scriptId":"u14"},
      "86ab48f766ea481bb5f1a7199a5b78f8":{
        "scriptId":"u15"},
      "160d7455f130416fa6d81dc2a0264d94":{
        "scriptId":"u16"}},
    "bf373003968c4fa8b9b3bb6463f0bd7e":{
      "scriptId":"u17"},
    "e82ca91a31dd4ea486141dadebbd0fce":{
      "scriptId":"u18"},
    "fff40588fd2d435189d79634dba8dfa1":{
      "scriptId":"u19"},
    "102e52f04a4543b2ade04beff9e6e798":{
      "scriptId":"u20"},
    "ef9d60b400ea4093a94b7bd9b9fcc999":{
      "scriptId":"u21"},
    "63312ec219a74afcb9969f5106af98b6":{
      "scriptId":"u22"},
    "2c0a6cadc7cc4b2fa8f37e8c48fa0453":{
      "scriptId":"u23"},
    "dbd9a4c8cc2c4a91be97c179d9554437":{
      "scriptId":"u24"},
    "2a3422d0fa354cadb354d6bc0f8249e4":{
      "scriptId":"u25"},
    "28398e60abec4b0fa2dd232722e3123e":{
      "scriptId":"u26"},
    "f9b078766bac4262b075ec284185010c":{
      "scriptId":"u27"},
    "62b149ef0e894d3790f133b6475d556e":{
      "scriptId":"u28"},
    "c21533eb798040b398ccb37fcb821492":{
      "scriptId":"u29"},
    "984c7f881af741cb9f5ee2e92f6a1667":{
      "scriptId":"u30"},
    "83cd9b3cec2b43b5a0032cde91c80da7":{
      "scriptId":"u31"},
    "3116ce60b4a54fd18cee923bb0512d25":{
      "scriptId":"u32"},
    "02c9b65dba2f47a2adbce2d050c88717":{
      "scriptId":"u33"},
    "e094edbb5cd8441c80071f287748d271":{
      "scriptId":"u34"},
    "eb6630df47db473dbd6bede25aabfefa":{
      "scriptId":"u35"},
    "81c37459f541483db4e1010161b74f4f":{
      "scriptId":"u36"},
    "fd32dd8921ea4e7aad253e8d3c1f9347":{
      "scriptId":"u37"},
    "f27e26a75899440e873b0b3709eecc73":{
      "scriptId":"u38"},
    "0ee2562200124b74b8f4a4fe560608ed":{
      "scriptId":"u39"},
    "adffdfe186e34563987b33be07270aba":{
      "scriptId":"u40"},
    "4abb932073894f878506dea2b953705c":{
      "scriptId":"u41"},
    "16e1a36dafc44e36a94522db14b9c28f":{
      "scriptId":"u42"},
    "eb9f17e19e5a4cb693d1eb3553117700":{
      "scriptId":"u43"},
    "7fa9e83bf90340ec832c5123cb5bba02":{
      "scriptId":"u44"},
    "0281a5f023f14fddbe4bee543dedccdd":{
      "scriptId":"u45"},
    "3729a1510f3d468a87f53ab7869aaa6b":{
      "scriptId":"u46"},
    "107a9995965a406992c01e6b37ad9cd9":{
      "scriptId":"u47"}}});