# Build settings
  
markdown: kramdown
permalink: pretty

sass:
 sass_dir: /assets/css
 style: expanded 
 sourcemap: auto
    
highlighter: rouge

encoding: utf-8

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'Gemfile', 'Gemfile.lock', 'the_design.psd', 'favicon.png', 'README.md']