#-------------------------------
# General Site Settings
# Site settings
baseurl: ""
url: "http://byronbuckley.com"
social_username: komplexb
twitter_username: komplexb
bitbucket_username:  komplexb
github_username:  komplexb
instagram_username:  komplexb

gravatar: byronbuckley@live.com
gravatar_alternate: komplexxx@gmail.com

title: Byron Buckley
email: hello@byronbuckley.com
description: Front-end Developer

# site default images and content are defined in all.sass

#bg-header: hero-bg.jpg
#bg-footer: hero-3.jpg
#logo: logo.svg

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Blog, url: 'http://blog.byronbuckley.com'}
- {name: Contact, url: '#contact'}

#-------------------------------
# About Section

#avatar: face.jpg # now defined in all.sass

blurb: <p><strong>Phasellus fringilla faucibus augue, eu sodales nisl accumsan non.</strong>Etiam gravida aliquet luctus. Mauris id accumsan nisl. Ut varius erat lacus, eu faucibus eros dapibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris elementum dolor urna, at scelerisque neque laoreet id. Etiam placerat risus viverra lectus eleifend pharetra. Proin tincidunt metus dui, nec vestibulum massa pretium id. Mauris nulla sem, iaculis eget enim eget, aliquam aliquet velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus at fringilla dui. Mauris eu leo nisi.</p>

skills:
- {name: Reading, value: '9'}
- {name: "Writin'", value: '7'}
- {name: "'rithmetic", value: '10'}
- {name: Skill 1, value: '6'}
- {name: Skill 2, value: '7'}
- {name: IxD, value: '5'}
- {name: UX Research, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.md'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.md'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.md'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.md'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.md'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.md'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.md'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.md'}

#-------------------------------
# Client Section

clients:
clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>Mandaremus varias doctrina nam nescius ita ingeniis.</strong> A esse ingeniis, hic minim relinqueret. Dolore expetendis despicationes, appellat tamen legam aliquip fore.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>WDolor aut admodum ita labore, e magna iis legam.</strong> Offendit malis quis ea fugiat quo e ingeniis ab eiusmod. Et lorem ullamco, eu esse do cillum.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Litteris quem et nescius concursionibus.</strong> Sed hic illum expetendis o incididunt dolore laboris. Est o magna excepteur ea te varias commodo occaecat.</p>',
  logo: 'logo4.png'}
  
#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'twitter.com/komplexb', platform: 'Twitter'}
- {icon: 'bitbucket', link: 'bitbucket.com/komplexb', platform: 'Bitbucket'}
- {icon: 'github', link: 'github.com/komplexb', platform: 'GitHub'}
- {icon: 'linkedin', link: 'linkedin.com/byronbuckley', platform: 'LinkedIn'}
- {icon: 'flickr', link: 'photos.byronbuckley.com', platform: 'Flickr'}
- {icon: 'instagram', link: 'instagram.com/komplexb', platform: 'Instagram'}
