#-------------------------------
# General Site Settings
# Site settings
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

title: Byron Buckley
email: hello@byronbuckley.com
description: Front-end // Interaction Design // Photography

# site default images and content

bg-header: hero-bg.jpg
bg-footer: hero-3.jpg
logo: logo.svg

menu:
- {name: About Me, url: '#about-me'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#-------------------------------
# About Section

avatar: face.jpg

blurb: <p><strong>Phasellus fringilla faucibus augue, eu sodales nisl accumsan non.</strong>Etiam gravida aliquet luctus. Mauris id accumsan nisl. Ut varius erat lacus, eu faucibus eros dapibus sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris elementum dolor urna, at scelerisque neque laoreet id. Etiam placerat risus viverra lectus eleifend pharetra. Proin tincidunt metus dui, nec vestibulum massa pretium id. Mauris nulla sem, iaculis eget enim eget, aliquam aliquet velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus at fringilla dui. Mauris eu leo nisi.</p>

skills:
- {name: Reading, value: '9'}
- {name: "Writin'", value: '7'}
- {name: "'rithmetic", value: '10'}
- {name: Skill 1, value: '6'}
- {name: Skill 2, value: '7'}
- {name: IxD, value: '5'}
- {name: UX Research, value: '8'}
- {name: Programming, value: '6'}

#-------------------------------
# Work Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.md'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.md'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.md'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.md'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.md'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.md'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.md'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.md'}