$axure.loadCurrentPage({
  "url":"notifyer.html",
  "generationDate":new Date(1376533200718.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"DroplistOption"],
  "page":{
    "packageId":"cb34b017a0ea443cb2065381e8854e1a",
    "type":"Axure:Page",
    "name":"Notifyer",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec03b690699d4984bcfdd95fe6f27ee4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":12,
              "y":55},
            "size":{
              "width":480,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85717ba91e014b199439f9e44d9b424b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":12,
                  "y":55},
                "size":{
                  "width":480,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b88ac2dfe07140bbbd6e925b6c5059f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":8},
            "size":{
              "width":121,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dac1770226d4f108bc585b4bd36c10f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":8},
                "size":{
                  "width":121,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"726c2274e0054cf1a41a4e2dba1e4414",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":133.000015258789},
            "size":{
              "width":610,
              "height":341}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0bc88e99b714183908b102c3ed5a382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":133.000015258789},
                "size":{
                  "width":610,
                  "height":341}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u4.png"}},
{
          "id":"bd397d9e336e4ee5aa16d83db07608d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":12,
              "y":111.000015258789},
            "size":{
              "width":300,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd02f8a776684b61aa8e11cfd0f1cae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":12,
                  "y":111.000015258789},
                "size":{
                  "width":300,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u6.png"}},
{
          "id":"d3d3144218f04ca9b5ff9f7741c29d77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":530},
            "size":{
              "width":180,
              "height":357}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8b02a79e2748c9aeec863e7ce2e150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":530},
                "size":{
                  "width":180,
                  "height":357}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u8.png"}},
{
          "id":"d5b09016d0674cd2b5a01496e866c737",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":12,
              "y":501},
            "size":{
              "width":300,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8ec8b0423764ec685fbece54e6f4fb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":12,
                  "y":501},
                "size":{
                  "width":300,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u10.png"}},
{
          "id":"3e0e12923273476d91a32d6602ec6127",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":422,
              "y":528},
            "size":{
              "width":180,
              "height":357}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4f7cc48ad9e48e087900141c6f0e552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":422,
                  "y":528},
                "size":{
                  "width":180,
                  "height":357}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u12.png"}},
{
          "id":"7a66aa91a9f24a0ba6c4a049391a07d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":392,
              "y":501},
            "size":{
              "width":300,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd3b8913fac64d439edba55a6ffb86f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":392,
                  "y":501},
                "size":{
                  "width":300,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u14.png"}},
{
          "id":"5c5a1d8f2378483d986bfe100133d2b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":985},
            "size":{
              "width":538,
              "height":326}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b29d8bda6a234196a5962cc3ad4beb19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":985},
                "size":{
                  "width":538,
                  "height":326}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u16.png"}},
{
          "id":"513f45542c594424a73c9404597887c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "paddingTop":"10",
            "paddingBottom":"10",
            "location":{
              "x":192,
              "y":958},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a4c58d8a5584ebabedf14bc6ddbbbb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "paddingTop":"10",
                "paddingBottom":"10",
                "location":{
                  "x":192,
                  "y":958},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notifyer/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec03b690699d4984bcfdd95fe6f27ee4":{
      "scriptId":"u0"},
    "85717ba91e014b199439f9e44d9b424b":{
      "scriptId":"u1"},
    "b88ac2dfe07140bbbd6e925b6c5059f6":{
      "scriptId":"u2"},
    "9dac1770226d4f108bc585b4bd36c10f":{
      "scriptId":"u3"},
    "726c2274e0054cf1a41a4e2dba1e4414":{
      "scriptId":"u4"},
    "b0bc88e99b714183908b102c3ed5a382":{
      "scriptId":"u5"},
    "bd397d9e336e4ee5aa16d83db07608d8":{
      "scriptId":"u6"},
    "fd02f8a776684b61aa8e11cfd0f1cae7":{
      "scriptId":"u7"},
    "d3d3144218f04ca9b5ff9f7741c29d77":{
      "scriptId":"u8"},
    "7a8b02a79e2748c9aeec863e7ce2e150":{
      "scriptId":"u9"},
    "d5b09016d0674cd2b5a01496e866c737":{
      "scriptId":"u10"},
    "b8ec8b0423764ec685fbece54e6f4fb0":{
      "scriptId":"u11"},
    "3e0e12923273476d91a32d6602ec6127":{
      "scriptId":"u12"},
    "b4f7cc48ad9e48e087900141c6f0e552":{
      "scriptId":"u13"},
    "7a66aa91a9f24a0ba6c4a049391a07d1":{
      "scriptId":"u14"},
    "cd3b8913fac64d439edba55a6ffb86f5":{
      "scriptId":"u15"},
    "5c5a1d8f2378483d986bfe100133d2b5":{
      "scriptId":"u16"},
    "b29d8bda6a234196a5962cc3ad4beb19":{
      "scriptId":"u17"},
    "513f45542c594424a73c9404597887c1":{
      "scriptId":"u18"},
    "0a4c58d8a5584ebabedf14bc6ddbbbb1":{
      "scriptId":"u19"}}});