$axure.loadCurrentPage({
  "url":"schedule_1.html",
  "generationDate":new Date(1376533204618.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"DroplistOption"],
  "page":{
    "packageId":"015dd9a114a64c26a171af9ea2d442c0",
    "type":"Axure:Page",
    "name":"Schedule",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"25",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"Set text on Alternate Window/Current Page Label equal to &quot;Schedule&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetWidgetRichText",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["f9afa45479304aaa96c0e2c9582810e4",
"3c5c5d03ce5f4af3a5cb6c672794a8d9"]},
{
                          "exprType":"htmlLiteral",
                          "value":"<p style=\"text-align:right;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:right;line-height:normal;\">Schedule</span></p>",
                          "localVariables":{
},
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"f9afa45479304aaa96c0e2c9582810e4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"b281c3f7526b4bb6bad46249f3c6841d"},
{
          "id":"bf373003968c4fa8b9b3bb6463f0bd7e",
          "label":"Save/Revert Modal",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":9,
              "y":9.19999694824219},
            "size":{
              "width":530,
              "height":322},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f1e012e55083443a8a99dc35889f5425",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e82ca91a31dd4ea486141dadebbd0fce",
                  "label":"",
                  "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FCCCCCC},
                    "size":{
                      "width":530,
                      "height":322}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fff40588fd2d435189d79634dba8dfa1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7FCCCCCC},
                        "size":{
                          "width":530,
                          "height":322}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/u18.png"}},
{
                  "id":"102e52f04a4543b2ade04beff9e6e798",
                  "label":"ModalStatusText",
                  "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontWeight":"bold",
                    "location":{
                      "x":189,
                      "y":113},
                    "size":{
                      "width":180,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef9d60b400ea4093a94b7bd9b9fcc999",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontWeight":"bold",
                        "location":{
                          "x":189,
                          "y":113},
                        "size":{
                          "width":180,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/modalstatustext_u20.png"}},
{
                  "id":"63312ec219a74afcb9969f5106af98b6",
                  "label":"Loading Small",
                  "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":323,
                      "y":145},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c0a6cadc7cc4b2fa8f37e8c48fa0453",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bf373003968c4fa8b9b3bb6463f0bd7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":323,
                          "y":145},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/loading_small_u22.gif"}}]}]},
{
          "id":"dbd9a4c8cc2c4a91be97c179d9554437",
          "label":"Schedule Text",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":52},
            "size":{
              "width":499,
              "height":25}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Allows user to type in a schedule, or it displays what the user has selected below."}},
{
          "id":"2a3422d0fa354cadb354d6bc0f8249e4",
          "label":"Save Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":352,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28398e60abec4b0fa2dd232722e3123e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":352,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Saving...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["ef9d60b400ea4093a94b7bd9b9fcc999"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Saving...</span></p>",
                                "localVariables":{
},
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Send Save/Revert Modal to Back",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":false}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Save Changes on this Screen"},
          "images":{
            "normal~":"images/tags/save_changes_u30.png",
            "mouseOver~":"images/tags/save_changes_u30.png"}},
{
          "id":"f9b078766bac4262b075ec284185010c",
          "label":"Revert Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":444,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b149ef0e894d3790f133b6475d556e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":444,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Reverting...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["ef9d60b400ea4093a94b7bd9b9fcc999"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Reverting...</span></p>",
                                "localVariables":{
},
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Send Save/Revert Modal to Back",
                      "panelPaths":[{
                          "panelPath":["bf373003968c4fa8b9b3bb6463f0bd7e"],
                          "setOrderInfo":{
                            "bringToFront":false}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Revert changes to the settings prior to loading the page."},
          "images":{
            "normal~":"images/tags/revert_changes_u32.png",
            "mouseOver~":"images/tags/revert_changes_u32.png"}},
{
          "id":"c21533eb798040b398ccb37fcb821492",
          "label":"Suspend Notifcations",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "location":{
              "x":322,
              "y":88},
            "size":{
              "width":202,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"984c7f881af741cb9f5ee2e92f6a1667",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "location":{
                  "x":322,
                  "y":88},
                "size":{
                  "width":202,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If is selected of Suspend Notifcations equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["c21533eb798040b398ccb37fcb821492"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"Disable Recurrence,<br>Mid Morning,<br>Mid Afternoon,<br>Noon,<br>Morning,<br>Early Morning,<br>Schedule Text,<br>Afternoon,<br>Late Night,<br>Evening",
                      "pathToInfo":[{
                          "objectPath":["107a9995965a406992c01e6b37ad9cd9"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["0ee2562200124b74b8f4a4fe560608ed"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["fd32dd8921ea4e7aad253e8d3c1f9347"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["eb6630df47db473dbd6bede25aabfefa"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["02c9b65dba2f47a2adbce2d050c88717"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["83cd9b3cec2b43b5a0032cde91c80da7"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["dbd9a4c8cc2c4a91be97c179d9554437"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["4abb932073894f878506dea2b953705c"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["eb9f17e19e5a4cb693d1eb3553117700"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["0281a5f023f14fddbe4bee543dedccdd"],
                          "enableDisableInfo":{
                            "enable":false}}]}]},
{
                  "description":"Case 2<br> (Else If is selected of Suspend Notifcations equals false)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["c21533eb798040b398ccb37fcb821492"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"Enable Schedule Text,<br>Early Morning,<br>Morning,<br>Noon,<br>Mid Afternoon,<br>Mid Morning,<br>Recurrence,<br>Evening,<br>Late Night,<br>Afternoon",
                      "pathToInfo":[{
                          "objectPath":["dbd9a4c8cc2c4a91be97c179d9554437"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["83cd9b3cec2b43b5a0032cde91c80da7"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["02c9b65dba2f47a2adbce2d050c88717"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["eb6630df47db473dbd6bede25aabfefa"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["fd32dd8921ea4e7aad253e8d3c1f9347"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["0ee2562200124b74b8f4a4fe560608ed"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["107a9995965a406992c01e6b37ad9cd9"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["0281a5f023f14fddbe4bee543dedccdd"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["eb9f17e19e5a4cb693d1eb3553117700"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["4abb932073894f878506dea2b953705c"],
                          "enableDisableInfo":{
                            "enable":true}}]}]}]}}},
{
          "id":"83cd9b3cec2b43b5a0032cde91c80da7",
          "label":"Early Morning",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":127},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3116ce60b4a54fd18cee923bb0512d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":127},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"02c9b65dba2f47a2adbce2d050c88717",
          "label":"Morning",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":170},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e094edbb5cd8441c80071f287748d271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":170},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"eb6630df47db473dbd6bede25aabfefa",
          "label":"Noon",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":251},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81c37459f541483db4e1010161b74f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":251},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"fd32dd8921ea4e7aad253e8d3c1f9347",
          "label":"Mid Afternoon",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":125},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27e26a75899440e873b0b3709eecc73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":125},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"0ee2562200124b74b8f4a4fe560608ed",
          "label":"Mid Morning",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":25,
              "y":211},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adffdfe186e34563987b33be07270aba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":25,
                  "y":211},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"4abb932073894f878506dea2b953705c",
          "label":"Afternoon",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":168},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e1a36dafc44e36a94522db14b9c28f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":168},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"eb9f17e19e5a4cb693d1eb3553117700",
          "label":"Late Night",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":250},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fa9e83bf90340ec832c5123cb5bba02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":250},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"0281a5f023f14fddbe4bee543dedccdd",
          "label":"Evening",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "stateStyles":{
              "selected":{
                "fontWeight":"bold"},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":322,
              "y":210},
            "size":{
              "width":202,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3729a1510f3d468a87f53ab7869aaa6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold"},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1}}},
                "location":{
                  "x":322,
                  "y":210},
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set is selected of This equal to &quot;toggle&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false},
{
                                "exprType":"stringLiteral",
                                "value":"toggle",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/schedule/early_morning_u31.png",
            "selected~":"images/schedule/early_morning_u31_selected.png",
            "disabled~":"images/schedule/early_morning_u31_disabled.png"}},
{
          "id":"107a9995965a406992c01e6b37ad9cd9",
          "label":"Recurrence",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":85},
            "size":{
              "width":202,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "b281c3f7526b4bb6bad46249f3c6841d":{
      "packageId":"b281c3f7526b4bb6bad46249f3c6841d",
      "type":"Axure:Master",
      "name":"Alternate Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd52a235e2b14d2abfa6555b2ece48e1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":530,
                "height":317}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a68fbf401bd468b869c5cb7dd1805bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":10},
                  "size":{
                    "width":530,
                    "height":317}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"dff2e843ec55478998fe0727379bbd91",
            "label":"Menu",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontWeight":"bold",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "stateStyles":{
                "disabled":{
}},
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":36,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"add0756193ea4fd69ea7eca016df382e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontWeight":"bold",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "stateStyles":{
                    "disabled":{
}},
                  "location":{
                    "x":9,
                    "y":10},
                  "size":{
                    "width":36,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelOrder",
                        "description":"Bring Main Menu to Front ",
                        "panelPaths":[{
                            "panelPath":["29f1d92ea44a43bd94b801fe1ee7f6c9"],
                            "setOrderInfo":{
                              "bringToFront":true}}]},
{
                        "action":"fadeWidget",
                        "description":"Toggle Main Menu",
                        "objectsToFades":[{
                            "objectPath":["29f1d92ea44a43bd94b801fe1ee7f6c9"],
                            "fadeInfo":{
                              "fadeType":"toggle",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/tags_1/menu_u3.png",
              "disabled~":"images/tags_1/menu_u3_disabled.png"}},
{
            "id":"800700a235cb4e4aa1823b39dd2bc437",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold Italic', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "fontStyle":"italic",
              "location":{
                "x":54,
                "y":12},
              "size":{
                "width":150,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9e54fef75d44b2da70077660a7ddfeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold Italic', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "fontStyle":"italic",
                  "location":{
                    "x":54,
                    "y":12},
                  "size":{
                    "width":150,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Tags in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"tags_1.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "annotation":{
              "Description":"Back to tags page which serves as home/root of app."},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"de98b9442d434d668d3e70fea87b099a",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":53,
                "y":30},
              "size":{
                "width":184,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/tags_1/u7_line.png"}},
{
            "id":"29f1d92ea44a43bd94b801fe1ee7f6c9",
            "label":"Main Menu",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":9,
                "y":35},
              "size":{
                "width":106,
                "height":68},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"2a2aff43b16a40ba941b2dd5bfa589da",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"df4a4976bfc34b86b8f37b5435b81744",
                    "label":"",
                    "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                    "type":"menuObject",
                    "styleType":"menuObject",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":106,
                        "height":66}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9c1b44acaafb45bea2bf13ba8c81ed2a",
                        "label":"",
                        "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                        "type":"table",
                        "styleType":"table",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":3,
                            "y":3},
                          "size":{
                            "width":100,
                            "height":60}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"353431c2900846f9835b0333cd1a0f30",
                            "label":"",
                            "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                            "type":"tableCell",
                            "styleType":"tableCell",
                            "visible":true,
                            "style":{
                              "underline":true,
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"23ee94b399b7486ba3fe9f379885e60c",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "underline":true,
                                  "horizontalAlignment":"center",
                                  "verticalAlignment":"middle",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1},
                                  "size":{
                                    "width":100,
                                    "height":20}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"Case 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"Open Login in Current Window",
                                        "target":{
                                          "targetType":"page",
                                          "url":"login_1.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"images/tags_1/u11.png"}},
{
                            "id":"0543911135614510bd9ca8b740e0c44f",
                            "label":"",
                            "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                            "type":"tableCell",
                            "styleType":"tableCell",
                            "visible":true,
                            "style":{
                              "underline":true,
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1},
                              "location":{
                                "x":0,
                                "y":20},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"62609261a892478ba9a144629d86253d",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "underline":true,
                                  "horizontalAlignment":"center",
                                  "verticalAlignment":"middle",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1},
                                  "location":{
                                    "x":0,
                                    "y":20},
                                  "size":{
                                    "width":100,
                                    "height":20}},
                                "adaptiveStyles":{
}}],
                            "annotation":{
                              "Description":"Contextual Help"},
                            "images":{
                              "normal~":"images/tags_1/u11.png"}},
{
                            "id":"a28d34e46b0e4ed399d75f60f566b9f4",
                            "label":"",
                            "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                            "type":"tableCell",
                            "styleType":"tableCell",
                            "visible":true,
                            "style":{
                              "underline":true,
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0000FF,
                                "opacity":1},
                              "location":{
                                "x":0,
                                "y":40},
                              "size":{
                                "width":100,
                                "height":20}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"f43b9aee35e945ff8050631dcb2a45f0",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"29f1d92ea44a43bd94b801fe1ee7f6c9",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "underline":true,
                                  "horizontalAlignment":"center",
                                  "verticalAlignment":"middle",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0000FF,
                                    "opacity":1},
                                  "location":{
                                    "x":0,
                                    "y":40},
                                  "size":{
                                    "width":100,
                                    "height":20}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"images/tags_1/u15.png"}}]}]}]}]},
{
            "id":"9c9173e9f77a489b94423d94b6d04943",
            "label":"Current Page Label",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Bold', 'Arial'",
              "fontSize":"15px",
              "fontWeight":"700",
              "horizontalAlignment":"right",
              "location":{
                "x":347,
                "y":15},
              "size":{
                "width":185,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3c5c5d03ce5f4af3a5cb6c672794a8d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Bold', 'Arial'",
                  "fontSize":"15px",
                  "fontWeight":"700",
                  "horizontalAlignment":"right",
                  "location":{
                    "x":347,
                    "y":15},
                  "size":{
                    "width":185,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "annotation":{
              "Description":"Lets user know which tag settings they are adjusting."},
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "f9afa45479304aaa96c0e2c9582810e4":{
      "scriptId":"u0",
      "fd52a235e2b14d2abfa6555b2ece48e1":{
        "scriptId":"u1"},
      "7a68fbf401bd468b869c5cb7dd1805bf":{
        "scriptId":"u2"},
      "dff2e843ec55478998fe0727379bbd91":{
        "scriptId":"u3"},
      "add0756193ea4fd69ea7eca016df382e":{
        "scriptId":"u4"},
      "800700a235cb4e4aa1823b39dd2bc437":{
        "scriptId":"u5"},
      "b9e54fef75d44b2da70077660a7ddfeb":{
        "scriptId":"u6"},
      "de98b9442d434d668d3e70fea87b099a":{
        "scriptId":"u7"},
      "29f1d92ea44a43bd94b801fe1ee7f6c9":{
        "scriptId":"u8"},
      "df4a4976bfc34b86b8f37b5435b81744":{
        "scriptId":"u9"},
      "9c1b44acaafb45bea2bf13ba8c81ed2a":{
        "scriptId":"u10"},
      "353431c2900846f9835b0333cd1a0f30":{
        "scriptId":"u11"},
      "23ee94b399b7486ba3fe9f379885e60c":{
        "scriptId":"u12"},
      "0543911135614510bd9ca8b740e0c44f":{
        "scriptId":"u13"},
      "62609261a892478ba9a144629d86253d":{
        "scriptId":"u14"},
      "a28d34e46b0e4ed399d75f60f566b9f4":{
        "scriptId":"u15"},
      "f43b9aee35e945ff8050631dcb2a45f0":{
        "scriptId":"u16"},
      "9c9173e9f77a489b94423d94b6d04943":{
        "scriptId":"u17"},
      "3c5c5d03ce5f4af3a5cb6c672794a8d9":{
        "scriptId":"u18"}},
    "bf373003968c4fa8b9b3bb6463f0bd7e":{
      "scriptId":"u19"},
    "e82ca91a31dd4ea486141dadebbd0fce":{
      "scriptId":"u20"},
    "fff40588fd2d435189d79634dba8dfa1":{
      "scriptId":"u21"},
    "102e52f04a4543b2ade04beff9e6e798":{
      "scriptId":"u22"},
    "ef9d60b400ea4093a94b7bd9b9fcc999":{
      "scriptId":"u23"},
    "63312ec219a74afcb9969f5106af98b6":{
      "scriptId":"u24"},
    "2c0a6cadc7cc4b2fa8f37e8c48fa0453":{
      "scriptId":"u25"},
    "dbd9a4c8cc2c4a91be97c179d9554437":{
      "scriptId":"u26"},
    "2a3422d0fa354cadb354d6bc0f8249e4":{
      "scriptId":"u27"},
    "28398e60abec4b0fa2dd232722e3123e":{
      "scriptId":"u28"},
    "f9b078766bac4262b075ec284185010c":{
      "scriptId":"u29"},
    "62b149ef0e894d3790f133b6475d556e":{
      "scriptId":"u30"},
    "c21533eb798040b398ccb37fcb821492":{
      "scriptId":"u31"},
    "984c7f881af741cb9f5ee2e92f6a1667":{
      "scriptId":"u32"},
    "83cd9b3cec2b43b5a0032cde91c80da7":{
      "scriptId":"u33"},
    "3116ce60b4a54fd18cee923bb0512d25":{
      "scriptId":"u34"},
    "02c9b65dba2f47a2adbce2d050c88717":{
      "scriptId":"u35"},
    "e094edbb5cd8441c80071f287748d271":{
      "scriptId":"u36"},
    "eb6630df47db473dbd6bede25aabfefa":{
      "scriptId":"u37"},
    "81c37459f541483db4e1010161b74f4f":{
      "scriptId":"u38"},
    "fd32dd8921ea4e7aad253e8d3c1f9347":{
      "scriptId":"u39"},
    "f27e26a75899440e873b0b3709eecc73":{
      "scriptId":"u40"},
    "0ee2562200124b74b8f4a4fe560608ed":{
      "scriptId":"u41"},
    "adffdfe186e34563987b33be07270aba":{
      "scriptId":"u42"},
    "4abb932073894f878506dea2b953705c":{
      "scriptId":"u43"},
    "16e1a36dafc44e36a94522db14b9c28f":{
      "scriptId":"u44"},
    "eb9f17e19e5a4cb693d1eb3553117700":{
      "scriptId":"u45"},
    "7fa9e83bf90340ec832c5123cb5bba02":{
      "scriptId":"u46"},
    "0281a5f023f14fddbe4bee543dedccdd":{
      "scriptId":"u47"},
    "3729a1510f3d468a87f53ab7869aaa6b":{
      "scriptId":"u48"},
    "107a9995965a406992c01e6b37ad9cd9":{
      "scriptId":"u49"}}});