$axure.loadCurrentPage({
  "url":"initial_design.html",
  "generationDate":new Date(1376533200832.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"DroplistOption"],
  "page":{
    "packageId":"2e54508d3eaf499dadf243ba91624e70",
    "type":"Axure:Page",
    "name":"Initial Design",
    "notes":{
      "Default":"<p><span>The initial design is largely geared toward a single user. Even though the user can choose to send his/her missives to a variety of users, everybody will get whatever it is the account owner has sent to himself.</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3d3b78a6bb20446b9ff07d2f6d77207f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":4},
            "size":{
              "width":1024,
              "height":736}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"913bec29d0244eadbfb3b6c08d65c9db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":4},
                "size":{
                  "width":1024,
                  "height":736}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/initial_design/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "3d3b78a6bb20446b9ff07d2f6d77207f":{
      "scriptId":"u0"},
    "913bec29d0244eadbfb3b6c08d65c9db":{
      "scriptId":"u1"}}});