$axure.loadCurrentPage({
  "url":"recipients.html",
  "generationDate":new Date(1376533203360.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"DroplistOption"],
  "page":{
    "packageId":"dd531cf7b6d24bba9531d5dd91c24e8d",
    "type":"Axure:Page",
    "name":"Recipients",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"25",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"Set is selected of Default Window/Recipients equal to &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["d79f9c92e2ad467b92aa2f1deb94c8fb",
"8d035b185fb84392afc1199c60a7c075"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"d79f9c92e2ad467b92aa2f1deb94c8fb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"1d0592bb516a414fa8b800f785045d87"},
{
          "id":"0907f13cd1464ac4b3e6cde8f1451ca1",
          "label":"Save/Revert Modal",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":9,
              "y":9},
            "size":{
              "width":530,
              "height":322},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"781946ae0efa4b089f18083f294bdc84",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bcd121b4ee5247bf875249298add31e9",
                  "label":"",
                  "parentDynamicPanel":"0907f13cd1464ac4b3e6cde8f1451ca1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FCCCCCC},
                    "size":{
                      "width":530,
                      "height":322}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bed29f46ad5f463f99c8c78f6e95b4b2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0907f13cd1464ac4b3e6cde8f1451ca1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7FCCCCCC},
                        "size":{
                          "width":530,
                          "height":322}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/u18.png"}},
{
                  "id":"735296ad8056416084fe9cc7c63eb943",
                  "label":"ModalStatusText",
                  "parentDynamicPanel":"0907f13cd1464ac4b3e6cde8f1451ca1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontWeight":"bold",
                    "location":{
                      "x":189,
                      "y":113},
                    "size":{
                      "width":180,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6abc67abaef94281b3184aaebea52842",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0907f13cd1464ac4b3e6cde8f1451ca1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontWeight":"bold",
                        "location":{
                          "x":189,
                          "y":113},
                        "size":{
                          "width":180,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/modalstatustext_u20.png"}},
{
                  "id":"97ae9ff3d90940f9abd90922f2969e78",
                  "label":"Loading Small",
                  "parentDynamicPanel":"0907f13cd1464ac4b3e6cde8f1451ca1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":323,
                      "y":145},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2961e91271e44b529beac55493832ab5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0907f13cd1464ac4b3e6cde8f1451ca1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":323,
                          "y":145},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/loading_small_u22.gif"}}]}]},
{
          "id":"bf8c905bbe6e41c8a06cbd49df6d0b98",
          "label":"Toggle Recipients",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":52},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c743e34b03745bd99a6569d1a08dc07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":52},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If is selected of Toggle Recipients equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["bf8c905bbe6e41c8a06cbd49df6d0b98"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"Disable listbox,<br>listbox,<br>(Text Field),<br>(Text Field),<br>Outlook,<br>Yahoo!,<br>Gmail",
                      "pathToInfo":[{
                          "objectPath":["49bd0d3e1fdb4ac18e00a82e3bec09b5"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["b5aacdd6814f41f486a68fe85d7f4512"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["090acf118ce84ab4b0a15cb012db6236"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["6d394720ac314ee18290ef9464a4e391"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["5b205e01bac34b92a1de7ae84ce5a7b5"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["1b3098ff3eac458e969b34bd85b374a4"],
                          "enableDisableInfo":{
                            "enable":false}},
{
                          "objectPath":["0ab53c1f65a044e9ad0f27b05c8748b6"],
                          "enableDisableInfo":{
                            "enable":false}}]}]},
{
                  "description":"Case 2<br> (Else If is selected of Toggle Recipients equals false)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["bf8c905bbe6e41c8a06cbd49df6d0b98"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"enableDisableWidgets",
                      "description":"Enable listbox,<br>listbox,<br>(Text Field),<br>(Text Field),<br>Outlook,<br>Gmail,<br>Yahoo!",
                      "pathToInfo":[{
                          "objectPath":["49bd0d3e1fdb4ac18e00a82e3bec09b5"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["b5aacdd6814f41f486a68fe85d7f4512"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["090acf118ce84ab4b0a15cb012db6236"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["6d394720ac314ee18290ef9464a4e391"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["5b205e01bac34b92a1de7ae84ce5a7b5"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["0ab53c1f65a044e9ad0f27b05c8748b6"],
                          "enableDisableInfo":{
                            "enable":true}},
{
                          "objectPath":["1b3098ff3eac458e969b34bd85b374a4"],
                          "enableDisableInfo":{
                            "enable":true}}]}]}]}},
          "annotation":{
            "Description":"When enabled, this will send only to the account holders email address."}},
{
          "id":"68821bdd51874b9992c03a6f790b00c4",
          "label":"Save Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":352,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23c4564f32e844a2943151519c5ed5f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":352,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Saving...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["6abc67abaef94281b3184aaebea52842"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Saving...</span></p>",
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "setOrderInfo":{
                            "bringToFront":true}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Save Changes on this Screen"},
          "images":{
            "normal~":"images/tags/save_changes_u30.png",
            "mouseOver~":"images/tags/save_changes_u30.png"}},
{
          "id":"8251c268ac714540b5a19c12aa0e261b",
          "label":"Revert Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":444,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd09dfb6908041fc9f4ee2eefdfd57cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":444,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Reverting...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["6abc67abaef94281b3184aaebea52842"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Reverting...</span></p>",
                                "localVariables":{
},
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["0907f13cd1464ac4b3e6cde8f1451ca1"],
                          "setOrderInfo":{
                            "bringToFront":true}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Revert changes to the settings prior to loading the page."},
          "images":{
            "normal~":"images/tags/revert_changes_u32.png",
            "mouseOver~":"images/tags/revert_changes_u32.png"}},
{
          "id":"44dc79c34c7249d38301c88acdb2b8d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":24,
              "y":103},
            "size":{
              "width":185,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b069bf37d9014dcdbc66201a969d76f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":24,
                  "y":103},
                "size":{
                  "width":185,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49bd0d3e1fdb4ac18e00a82e3bec09b5",
          "label":"listbox",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":171},
            "size":{
              "width":222,
              "height":106}},
          "adaptiveStyles":{
}},
{
          "id":"09ca7d0cec5c4a9cbe186ba553826e2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":298,
              "y":103},
            "size":{
              "width":187,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6831902abcd04eeab9c8ecca98ef99dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":298,
                  "y":103},
                "size":{
                  "width":187,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5aacdd6814f41f486a68fe85d7f4512",
          "label":"listbox",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":171},
            "size":{
              "width":225,
              "height":104}},
          "adaptiveStyles":{
}},
{
          "id":"090acf118ce84ab4b0a15cb012db6236",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":24.5,
              "y":127},
            "size":{
              "width":222,
              "height":34}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Typing into this box should filter the list of unused email addresses below."},
          "placeholderText":"filter list..."},
{
          "id":"6d394720ac314ee18290ef9464a4e391",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":298.5,
              "y":127},
            "size":{
              "width":225,
              "height":34}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Typing into this box should filter the list of email addresses below."},
          "placeholderText":"filter list..."},
{
          "id":"5b205e01bac34b92a1de7ae84ce5a7b5",
          "label":"Outlook",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":24,
              "y":77},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03299a5e2aa14c43a67aad1c4e4d02b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":24,
                  "y":77},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"Retrieve contact list from external account and place in applications contact list."},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ab53c1f65a044e9ad0f27b05c8748b6",
          "label":"Gmail",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":243.999984741211,
              "y":77},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540755e6d32c44c1906a9192095c2df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":243.999984741211,
                  "y":77},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"Retrieve contact list from external account and place in applications contact list."},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b3098ff3eac458e969b34bd85b374a4",
          "label":"Yahoo!",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "underline":true,
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":468,
              "y":77},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037cfc2ceb8c45c78d58f150c866d1b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":468,
                  "y":77},
                "size":{
                  "width":60,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"Retrieve contact list from external account and place in applications contact list."},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08477fd290b74c94ad13e2921a4f4cb3",
          "label":"Add New Address",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":135},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b23a2abddbe459c94b68020ee9adaec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":135},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"The add new address function will add the new address to the existing subscribers list."},
          "images":{
            "normal~":"images/recipients/add_new_address_u44.png"}},
{
          "id":"1c8f567043624db89297e8a375589c71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":133.5},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74d3177748d840a18bf97f2258dfccb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":133.5},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"153e535865534c338a26d7b3023cbd98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":168.5},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a89efca0e8564a83b3201ceb24bc2641",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":168.5},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"e72f7757ee2144ffa0421c13ffb8ee8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":203.5},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39033323ada44131bdf0a793e7e64f8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":203.5},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"622ab6d507464a7ea1c2b175ba2e3104",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":238.5},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44d14a7c169e48c59c5aae23ec82a27d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":238.5},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"201421b35d674321a155028227ea5d90",
          "label":"Link",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":171},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d10a8dc79dc341fcb066b813eddab556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":171},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"Clicking the X should remove this email address and add it back to the contact list."},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"3923b76da05740a0ae6cf925ea79139c",
          "label":"Link",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":186},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec82d116b85b4cbe856f221a473c19f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":186},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"6f1cc42c2f2e4f969759bec22622be1b",
          "label":"Link",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":490,
              "y":204},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7768325466a14ce781fe91d9833e34c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":490,
                  "y":204},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "1d0592bb516a414fa8b800f785045d87":{
      "packageId":"1d0592bb516a414fa8b800f785045d87",
      "type":"Axure:Master",
      "name":"Default Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd52a235e2b14d2abfa6555b2ece48e1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":530,
                "height":317}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a68fbf401bd468b869c5cb7dd1805bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":10},
                  "size":{
                    "width":530,
                    "height":317}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"20a59c4b535c416baab96a462c880970",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":531,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ac3c7732bf5044fa8054f0d8385529c2",
                "label":"Navigation",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "location":{
                    "x":3,
                    "y":3},
                  "size":{
                    "width":525,
                    "height":20}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"1f49a2bfeb324fe3874615bd77106242",
                    "label":"Home",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62cd4166ce5f41e58c21ab9aa43a0eb7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Dashboard in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"dashboard.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"819ac8a5aeba4eeca8fb7de2d6d8d6de",
                    "label":"Tags",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":100,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6d08094da54147e6b1ee2f049735a9f0",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":100,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Tags in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"tags.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"0b97a9aadb1b4ebf81ad1e88d6e74327",
                    "label":"Schedule",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":200,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9d47f61c666a4862bf3794d188181ef2",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":200,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Schedule in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"schedule.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"86ab48f766ea481bb5f1a7199a5b78f8",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":492,
                        "y":0},
                      "size":{
                        "width":33,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"160d7455f130416fa6d81dc2a0264d94",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":492,
                            "y":0},
                          "size":{
                            "width":33,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u15.png",
                      "selected~":"images/dashboard/u15.png",
                      "mouseOver~":"images/dashboard/u15.png"}},
{
                    "id":"9167aff36ce0446c8cecb1c6c2196fd3",
                    "label":"Logout",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":400,
                        "y":0},
                      "size":{
                        "width":92,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f05d90b2abc54df48dbf10ade98840e5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":400,
                            "y":0},
                          "size":{
                            "width":92,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Login in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"login.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/logout_u13.png",
                      "selected~":"images/dashboard/logout_u13.png",
                      "mouseOver~":"images/dashboard/logout_u13.png"}},
{
                    "id":"8d035b185fb84392afc1199c60a7c075",
                    "label":"Recipients",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":300,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"32415f9939704c9d9f7ece4c939a347c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":300,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Recipients in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"recipients.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}}]}],
            "annotation":{
              "Description":"Bold the text of the corresponding button, to indicate the current location to the user."}}]}}},
  "objectPaths":{
    "d79f9c92e2ad467b92aa2f1deb94c8fb":{
      "scriptId":"u0",
      "fd52a235e2b14d2abfa6555b2ece48e1":{
        "scriptId":"u1"},
      "7a68fbf401bd468b869c5cb7dd1805bf":{
        "scriptId":"u2"},
      "20a59c4b535c416baab96a462c880970":{
        "scriptId":"u3"},
      "ac3c7732bf5044fa8054f0d8385529c2":{
        "scriptId":"u4"},
      "1f49a2bfeb324fe3874615bd77106242":{
        "scriptId":"u5"},
      "62cd4166ce5f41e58c21ab9aa43a0eb7":{
        "scriptId":"u6"},
      "819ac8a5aeba4eeca8fb7de2d6d8d6de":{
        "scriptId":"u7"},
      "6d08094da54147e6b1ee2f049735a9f0":{
        "scriptId":"u8"},
      "0b97a9aadb1b4ebf81ad1e88d6e74327":{
        "scriptId":"u9"},
      "9d47f61c666a4862bf3794d188181ef2":{
        "scriptId":"u10"},
      "8d035b185fb84392afc1199c60a7c075":{
        "scriptId":"u11"},
      "32415f9939704c9d9f7ece4c939a347c":{
        "scriptId":"u12"},
      "9167aff36ce0446c8cecb1c6c2196fd3":{
        "scriptId":"u13"},
      "f05d90b2abc54df48dbf10ade98840e5":{
        "scriptId":"u14"},
      "86ab48f766ea481bb5f1a7199a5b78f8":{
        "scriptId":"u15"},
      "160d7455f130416fa6d81dc2a0264d94":{
        "scriptId":"u16"}},
    "0907f13cd1464ac4b3e6cde8f1451ca1":{
      "scriptId":"u17"},
    "bcd121b4ee5247bf875249298add31e9":{
      "scriptId":"u18"},
    "bed29f46ad5f463f99c8c78f6e95b4b2":{
      "scriptId":"u19"},
    "735296ad8056416084fe9cc7c63eb943":{
      "scriptId":"u20"},
    "6abc67abaef94281b3184aaebea52842":{
      "scriptId":"u21"},
    "97ae9ff3d90940f9abd90922f2969e78":{
      "scriptId":"u22"},
    "2961e91271e44b529beac55493832ab5":{
      "scriptId":"u23"},
    "bf8c905bbe6e41c8a06cbd49df6d0b98":{
      "scriptId":"u24"},
    "5c743e34b03745bd99a6569d1a08dc07":{
      "scriptId":"u25"},
    "68821bdd51874b9992c03a6f790b00c4":{
      "scriptId":"u26"},
    "23c4564f32e844a2943151519c5ed5f1":{
      "scriptId":"u27"},
    "8251c268ac714540b5a19c12aa0e261b":{
      "scriptId":"u28"},
    "dd09dfb6908041fc9f4ee2eefdfd57cd":{
      "scriptId":"u29"},
    "44dc79c34c7249d38301c88acdb2b8d9":{
      "scriptId":"u30"},
    "b069bf37d9014dcdbc66201a969d76f0":{
      "scriptId":"u31"},
    "49bd0d3e1fdb4ac18e00a82e3bec09b5":{
      "scriptId":"u32"},
    "09ca7d0cec5c4a9cbe186ba553826e2e":{
      "scriptId":"u33"},
    "6831902abcd04eeab9c8ecca98ef99dc":{
      "scriptId":"u34"},
    "b5aacdd6814f41f486a68fe85d7f4512":{
      "scriptId":"u35"},
    "090acf118ce84ab4b0a15cb012db6236":{
      "scriptId":"u36"},
    "6d394720ac314ee18290ef9464a4e391":{
      "scriptId":"u37"},
    "5b205e01bac34b92a1de7ae84ce5a7b5":{
      "scriptId":"u38"},
    "03299a5e2aa14c43a67aad1c4e4d02b3":{
      "scriptId":"u39"},
    "0ab53c1f65a044e9ad0f27b05c8748b6":{
      "scriptId":"u40"},
    "540755e6d32c44c1906a9192095c2df5":{
      "scriptId":"u41"},
    "1b3098ff3eac458e969b34bd85b374a4":{
      "scriptId":"u42"},
    "037cfc2ceb8c45c78d58f150c866d1b0":{
      "scriptId":"u43"},
    "08477fd290b74c94ad13e2921a4f4cb3":{
      "scriptId":"u44"},
    "8b23a2abddbe459c94b68020ee9adaec":{
      "scriptId":"u45"},
    "1c8f567043624db89297e8a375589c71":{
      "scriptId":"u46"},
    "74d3177748d840a18bf97f2258dfccb3":{
      "scriptId":"u47"},
    "153e535865534c338a26d7b3023cbd98":{
      "scriptId":"u48"},
    "a89efca0e8564a83b3201ceb24bc2641":{
      "scriptId":"u49"},
    "e72f7757ee2144ffa0421c13ffb8ee8f":{
      "scriptId":"u50"},
    "39033323ada44131bdf0a793e7e64f8e":{
      "scriptId":"u51"},
    "622ab6d507464a7ea1c2b175ba2e3104":{
      "scriptId":"u52"},
    "44d14a7c169e48c59c5aae23ec82a27d":{
      "scriptId":"u53"},
    "201421b35d674321a155028227ea5d90":{
      "scriptId":"u54"},
    "d10a8dc79dc341fcb066b813eddab556":{
      "scriptId":"u55"},
    "3923b76da05740a0ae6cf925ea79139c":{
      "scriptId":"u56"},
    "ec82d116b85b4cbe856f221a473c19f8":{
      "scriptId":"u57"},
    "6f1cc42c2f2e4f969759bec22622be1b":{
      "scriptId":"u58"},
    "7768325466a14ce781fe91d9833e34c6":{
      "scriptId":"u59"}}});