$axure.loadCurrentPage({
  "url":"tags.html",
  "generationDate":new Date(1376533202279.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"AxStWidget",
"AxStXPosition",
"DroplistOption"],
  "page":{
    "packageId":"4c31088b5ff9488fa02ef265c486351e",
    "type":"Axure:Page",
    "name":"Tags",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "sketchFactor":"25",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"Set is selected of Default Window/Tags equal to &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "value":["d79f9c92e2ad467b92aa2f1deb94c8fb",
"819ac8a5aeba4eeca8fb7de2d6d8d6de"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"d79f9c92e2ad467b92aa2f1deb94c8fb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"1d0592bb516a414fa8b800f785045d87"},
{
          "id":"3e57d8fc4bfd48eba0409582b64174a9",
          "label":"Save/Revert Modal",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":9.20001220703125,
              "y":8.5},
            "size":{
              "width":530,
              "height":322},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a49b4ddd10544cb5bc8fc369a315d208",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"54dd31319c81439c9b668737b7388614",
                  "label":"",
                  "parentDynamicPanel":"3e57d8fc4bfd48eba0409582b64174a9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x7FCCCCCC},
                    "size":{
                      "width":530,
                      "height":322}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c6ac21c22b54762816a6d4e7c558cf8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e57d8fc4bfd48eba0409582b64174a9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x7FCCCCCC},
                        "size":{
                          "width":530,
                          "height":322}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/u18.png"}},
{
                  "id":"984d966178b14d48a106637b1b85998f",
                  "label":"ModalStatusText",
                  "parentDynamicPanel":"3e57d8fc4bfd48eba0409582b64174a9",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontWeight":"bold",
                    "location":{
                      "x":189,
                      "y":113},
                    "size":{
                      "width":180,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee4618a1e07141f39f91c533c4095e88",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e57d8fc4bfd48eba0409582b64174a9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontWeight":"bold",
                        "location":{
                          "x":189,
                          "y":113},
                        "size":{
                          "width":180,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/modalstatustext_u20.png"}},
{
                  "id":"e881231b5a62422b8cfb71ab0b256d5b",
                  "label":"Loading Small",
                  "parentDynamicPanel":"3e57d8fc4bfd48eba0409582b64174a9",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":323,
                      "y":145},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eecec619489942efbd4abff1fb3e6054",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3e57d8fc4bfd48eba0409582b64174a9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":323,
                          "y":145},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/tags/loading_small_u22.gif"}}]}]},
{
          "id":"ddcb79be5f2c4410bb83b8bcf9c87e55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":29,
              "y":55},
            "size":{
              "width":185,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf212047d9de4c9ea1f4462ad100316e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":29,
                  "y":55},
                "size":{
                  "width":185,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95604eb98fd946e899fbb9f49f303bba",
          "label":"listbox",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":135},
            "size":{
              "width":222,
              "height":132}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"List items are tags retrieved via Simplenote API."}},
{
          "id":"0a2a922a22714eb0967730e76a0c1cb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":303,
              "y":55},
            "size":{
              "width":187,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a50adb8dbcb64052a231444b6c34a8e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":303,
                  "y":55},
                "size":{
                  "width":187,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7834cdb965984d3ea773738ec3c1bc14",
          "label":"listbox",
          "type":"listBox",
          "styleType":"listBox",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":135},
            "size":{
              "width":225,
              "height":132}},
          "adaptiveStyles":{
}},
{
          "id":"d985af1d5bc64859bdd5654607919ac8",
          "label":"Save Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":352,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac9760290ee646b2bf5e5f5b668dfe40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":352,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Saving...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["ee4618a1e07141f39f91c533c4095e88"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Saving...</span></p>",
                                "localVariables":{
},
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Send Save/Revert Modal to Back",
                      "panelPaths":[{
                          "panelPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "setOrderInfo":{
                            "bringToFront":false}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Save Changes on this Screen"},
          "images":{
            "normal~":"images/tags/save_changes_u30.png",
            "mouseOver~":"images/tags/save_changes_u30.png"}},
{
          "id":"d1a8a7b7af3e4da0be57a270f9af7d41",
          "label":"Revert Changes",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3300},
            "location":{
              "x":444,
              "y":288},
            "size":{
              "width":84,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9943cd11d9474602884da2bec0b3c0a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3300},
                "location":{
                  "x":444,
                  "y":288},
                "size":{
                  "width":84,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on ModalStatusText equal to &quot;Reverting...&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "value":["ee4618a1e07141f39f91c533c4095e88"]},
{
                                "exprType":"htmlLiteral",
                                "value":"<p style=\"text-align:center;line-height:normal;\"><span style=\"font-family:'Arial Bold', 'Arial';font-weight:700;font-style:normal;font-size:13px;color:#333333;text-align:center;line-height:normal;\">Reverting...</span></p>",
                                "localVariables":{
},
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Bring Save/Revert Modal to Front ",
                      "panelPaths":[{
                          "panelPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"wait",
                      "description":"Wait 3000 ms",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"Hide Save/Revert Modal",
                      "objectsToFades":[{
                          "objectPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelOrder",
                      "description":"Send Save/Revert Modal to Back",
                      "panelPaths":[{
                          "panelPath":["3e57d8fc4bfd48eba0409582b64174a9"],
                          "setOrderInfo":{
                            "bringToFront":false}}]}]}]}},
          "tabbable":true,
          "annotation":{
            "Description":"Revert changes to the settings prior to loading the page."},
          "images":{
            "normal~":"images/tags/revert_changes_u32.png",
            "mouseOver~":"images/tags/revert_changes_u32.png"}},
{
          "id":"2ee7e715ec714772b4f8928df7cf55de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":135},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d679b64e7edc4dae98f1d6613c0922d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":135},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"7b8e0d5ed5d2428a84e5eff8ba1413fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":170},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a97b7feb604b4becbb8d391f5b24d0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":170},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"65c0994a85fe42fd9f652e6a4aa05041",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":205},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac3a9f4abb1f4fbf85d5fea79547d0e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":205},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"7173a830982e4b358bed577d45f440bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":240},
            "size":{
              "width":32,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e68eaccdef748e1b76f18e3a7f02d88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":240},
                "size":{
                  "width":32,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tags/u34.png"}},
{
          "id":"049b9c1ec6ba4987ab9ddce00d4c4979",
          "label":"Link",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":495,
              "y":138},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e283976632d3401f8ce648ab2b1c47cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":495,
                  "y":138},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "Description":"Clicking the X should remove this category and add it back to the available list."},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"85580281e52948f8a6fc0ed43302e88d",
          "label":"Link",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":495,
              "y":153},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c674a05a8dc2466594e26296d5ea32a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":495,
                  "y":153},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"697a9077841442f3b0efefd170de770c",
          "label":"Link",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontWeight":"bold",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "underline":true}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":495,
              "y":171},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adaf251b5d5d4fb681b4f481f12ab31f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontWeight":"bold",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "underline":true}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":495,
                  "y":171},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7b28d7a577444080b8a38d0908e7480c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":29,
              "y":84},
            "size":{
              "width":222,
              "height":34}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Typing into this box should filter the list of unused email addresses below."},
          "placeholderText":"filter list..."},
{
          "id":"80ad53df6da247c0b695896d50f9a3e1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":303,
              "y":84},
            "size":{
              "width":225,
              "height":34}},
          "adaptiveStyles":{
},
          "annotation":{
            "Description":"Typing into this box should filter the list of email addresses below."},
          "placeholderText":"filter list..."}]}},
  "masters":{
    "1d0592bb516a414fa8b800f785045d87":{
      "packageId":"1d0592bb516a414fa8b800f785045d87",
      "type":"Axure:Master",
      "name":"Default Window",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"fd52a235e2b14d2abfa6555b2ece48e1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":530,
                "height":317}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7a68fbf401bd468b869c5cb7dd1805bf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":10},
                  "size":{
                    "width":530,
                    "height":317}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/dashboard/u1.png"}},
{
            "id":"20a59c4b535c416baab96a462c880970",
            "label":"",
            "type":"menuObject",
            "styleType":"menuObject",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":10},
              "size":{
                "width":531,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ac3c7732bf5044fa8054f0d8385529c2",
                "label":"Navigation",
                "type":"table",
                "styleType":"table",
                "visible":true,
                "style":{
                  "location":{
                    "x":3,
                    "y":3},
                  "size":{
                    "width":525,
                    "height":20}},
                "adaptiveStyles":{
},
                "objects":[{
                    "id":"1f49a2bfeb324fe3874615bd77106242",
                    "label":"Home",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62cd4166ce5f41e58c21ab9aa43a0eb7",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Dashboard in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"dashboard.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"819ac8a5aeba4eeca8fb7de2d6d8d6de",
                    "label":"Tags",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":100,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6d08094da54147e6b1ee2f049735a9f0",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":100,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Tags in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"tags.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"0b97a9aadb1b4ebf81ad1e88d6e74327",
                    "label":"Schedule",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":200,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9d47f61c666a4862bf3794d188181ef2",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":200,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Schedule in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"schedule.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}},
{
                    "id":"86ab48f766ea481bb5f1a7199a5b78f8",
                    "label":"",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":492,
                        "y":0},
                      "size":{
                        "width":33,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"160d7455f130416fa6d81dc2a0264d94",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":492,
                            "y":0},
                          "size":{
                            "width":33,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/dashboard/u15.png",
                      "selected~":"images/dashboard/u15.png",
                      "mouseOver~":"images/dashboard/u15.png"}},
{
                    "id":"9167aff36ce0446c8cecb1c6c2196fd3",
                    "label":"Logout",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":400,
                        "y":0},
                      "size":{
                        "width":92,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f05d90b2abc54df48dbf10ade98840e5",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":400,
                            "y":0},
                          "size":{
                            "width":92,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Login in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"login.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/logout_u13.png",
                      "selected~":"images/dashboard/logout_u13.png",
                      "mouseOver~":"images/dashboard/logout_u13.png"}},
{
                    "id":"8d035b185fb84392afc1199c60a7c075",
                    "label":"Recipients",
                    "type":"tableCell",
                    "styleType":"tableCell",
                    "visible":true,
                    "style":{
                      "horizontalAlignment":"center",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0000FF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "underline":true},
                        "selected":{
                          "fontWeight":"bold"}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFFFFF},
                      "location":{
                        "x":300,
                        "y":0},
                      "size":{
                        "width":100,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"32415f9939704c9d9f7ece4c939a347c",
                        "label":"",
                        "isContained":true,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "horizontalAlignment":"center",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0000FF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "underline":true},
                            "selected":{
                              "fontWeight":"bold"}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFF},
                          "location":{
                            "x":300,
                            "y":0},
                          "size":{
                            "width":100,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Recipients in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"recipients.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/dashboard/home_u5.png",
                      "selected~":"images/dashboard/home_u5.png",
                      "mouseOver~":"images/dashboard/home_u5.png"}}]}],
            "annotation":{
              "Description":"Bold the text of the corresponding button, to indicate the current location to the user."}}]}}},
  "objectPaths":{
    "d79f9c92e2ad467b92aa2f1deb94c8fb":{
      "scriptId":"u0",
      "fd52a235e2b14d2abfa6555b2ece48e1":{
        "scriptId":"u1"},
      "7a68fbf401bd468b869c5cb7dd1805bf":{
        "scriptId":"u2"},
      "20a59c4b535c416baab96a462c880970":{
        "scriptId":"u3"},
      "ac3c7732bf5044fa8054f0d8385529c2":{
        "scriptId":"u4"},
      "1f49a2bfeb324fe3874615bd77106242":{
        "scriptId":"u5"},
      "62cd4166ce5f41e58c21ab9aa43a0eb7":{
        "scriptId":"u6"},
      "819ac8a5aeba4eeca8fb7de2d6d8d6de":{
        "scriptId":"u7"},
      "6d08094da54147e6b1ee2f049735a9f0":{
        "scriptId":"u8"},
      "0b97a9aadb1b4ebf81ad1e88d6e74327":{
        "scriptId":"u9"},
      "9d47f61c666a4862bf3794d188181ef2":{
        "scriptId":"u10"},
      "8d035b185fb84392afc1199c60a7c075":{
        "scriptId":"u11"},
      "32415f9939704c9d9f7ece4c939a347c":{
        "scriptId":"u12"},
      "9167aff36ce0446c8cecb1c6c2196fd3":{
        "scriptId":"u13"},
      "f05d90b2abc54df48dbf10ade98840e5":{
        "scriptId":"u14"},
      "86ab48f766ea481bb5f1a7199a5b78f8":{
        "scriptId":"u15"},
      "160d7455f130416fa6d81dc2a0264d94":{
        "scriptId":"u16"}},
    "3e57d8fc4bfd48eba0409582b64174a9":{
      "scriptId":"u17"},
    "54dd31319c81439c9b668737b7388614":{
      "scriptId":"u18"},
    "8c6ac21c22b54762816a6d4e7c558cf8":{
      "scriptId":"u19"},
    "984d966178b14d48a106637b1b85998f":{
      "scriptId":"u20"},
    "ee4618a1e07141f39f91c533c4095e88":{
      "scriptId":"u21"},
    "e881231b5a62422b8cfb71ab0b256d5b":{
      "scriptId":"u22"},
    "eecec619489942efbd4abff1fb3e6054":{
      "scriptId":"u23"},
    "ddcb79be5f2c4410bb83b8bcf9c87e55":{
      "scriptId":"u24"},
    "cf212047d9de4c9ea1f4462ad100316e":{
      "scriptId":"u25"},
    "95604eb98fd946e899fbb9f49f303bba":{
      "scriptId":"u26"},
    "0a2a922a22714eb0967730e76a0c1cb1":{
      "scriptId":"u27"},
    "a50adb8dbcb64052a231444b6c34a8e6":{
      "scriptId":"u28"},
    "7834cdb965984d3ea773738ec3c1bc14":{
      "scriptId":"u29"},
    "d985af1d5bc64859bdd5654607919ac8":{
      "scriptId":"u30"},
    "ac9760290ee646b2bf5e5f5b668dfe40":{
      "scriptId":"u31"},
    "d1a8a7b7af3e4da0be57a270f9af7d41":{
      "scriptId":"u32"},
    "9943cd11d9474602884da2bec0b3c0a3":{
      "scriptId":"u33"},
    "2ee7e715ec714772b4f8928df7cf55de":{
      "scriptId":"u34"},
    "d679b64e7edc4dae98f1d6613c0922d5":{
      "scriptId":"u35"},
    "7b8e0d5ed5d2428a84e5eff8ba1413fc":{
      "scriptId":"u36"},
    "a97b7feb604b4becbb8d391f5b24d0db":{
      "scriptId":"u37"},
    "65c0994a85fe42fd9f652e6a4aa05041":{
      "scriptId":"u38"},
    "ac3a9f4abb1f4fbf85d5fea79547d0e7":{
      "scriptId":"u39"},
    "7173a830982e4b358bed577d45f440bc":{
      "scriptId":"u40"},
    "2e68eaccdef748e1b76f18e3a7f02d88":{
      "scriptId":"u41"},
    "049b9c1ec6ba4987ab9ddce00d4c4979":{
      "scriptId":"u42"},
    "e283976632d3401f8ce648ab2b1c47cc":{
      "scriptId":"u43"},
    "85580281e52948f8a6fc0ed43302e88d":{
      "scriptId":"u44"},
    "c674a05a8dc2466594e26296d5ea32a6":{
      "scriptId":"u45"},
    "697a9077841442f3b0efefd170de770c":{
      "scriptId":"u46"},
    "adaf251b5d5d4fb681b4f481f12ab31f":{
      "scriptId":"u47"},
    "7b28d7a577444080b8a38d0908e7480c":{
      "scriptId":"u48"},
    "80ad53df6da247c0b695896d50f9a3e1":{
      "scriptId":"u49"}}});